site_name: System Design
docs_dir: system-design

nav:
  - Introduction: index.md
  - Governance:
      - Membership Levels: Governance/Membership-Levels.md
      - Organisational Structure: Governance/Organization-Structure.md
      - Steering Committee: Governance/Technical-Steering-Committee.md
      - Working Group: Governance/Working-Group.md
  - Organizational Roles: 
      - Editors: Organizational-Roles/Editors.md
      - Maintainers: Organizational-Roles/Maintainers.md
      - Members: Organizational-Roles/Participants.md
  - Contributing:
      - Placeholder: Contributing/placeholder.md
  - Approval Process:
      - Asynchronous Review and Approval: Approval-Process/Asynchronous-Review-and-Approval-process.md
      - Using Supermajority vote to achieve agreement: Approval-Process/Using-Supermajority-vote-to-achieve-agreement.md
      - Voting on Technical Issues: Approval-Process/Voting-on-Technical-Issues.md
  - Documentation:
      - Semantic-Versioning: Documentation/Semantic-Versioning.md
  - Technical Decision Making:
      - Decision Making: Technical-Decision-Making/Decision_Making.md
      - Handling Objections: Technical-Decision-Making/Handling-objections.md
      - Seeking Consensus: Technical-Decision-Making/Seeking_Consensus.md
  - Terminology and Conventions:
     - Definitions: Terminology-and-Conventions/Seeking_Consensus.md
     - Language: Terminology-and-Conventions/Language.md
  ##    - Device:
  ##  - Appendix:
  ##    - Management API Definition: margo-overview/personas.md
  - Management API Reference:
      - Overview: margo-api-reference/margo-api-specification.md
      - Workload API:
          - Desired State API:
              - Desired State: margo-api-reference/workload-api/desired-state-api/desired-state.md
          - Device API:
              - Device Capabilities: margo-api-reference/workload-api/device-api/device-capabilities.md
              - Deployment Status: margo-api-reference/workload-api/device-api/deployment-status.md
          - Onboarding API:
              - Device Onboarding: margo-api-reference/workload-api/onboarding-api/device-onboarding.md
              - Certificate Download: margo-api-reference/workload-api/onboarding-api/rootca-download.md

theme:
  name: material
  features:
    #- navigation.tabs
    #- navigation.settings
    #- navigation.top
    - navigation.tracking
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotations
    - content.code.copy
  language: en
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  logo: assets/margo_white.svg
  favicon: assets/favicon.ico
  palette:
    scheme: margo

markdown_extensions:
  - toc:
      toc_depth: 2

extra_css:
  - css/margo.css

extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#generator-notice
  generator: true
  homepage: https://margo.org
  copyright: Copyright &copy; 2024 Margo
  reponame: !ENV [GITHUB_REPOSITORY, "margo/operations"]
  commit: !ENV [GITHUB_SHA, "<unknown>"]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/margo
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/margo_project
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/margoproject/about/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Margoinitiative
    - icon: fontawesome/brands/discord
      link: http://chat.margo.org/

plugins:
  - search
  - markdownextradata:
      jinja_options:
        variable_start_string: =@=
        variable_end_string: =@=
  - privacy
